In [1]:
import numpy as np

In [2]:
height = 2
width = 3
data = np.arange(6).reshape((2, 3))
data

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
A = np.array([[1, 0],
              [0, -1]])

A

array([[ 1,  0],
       [ 0, -1]])

In [5]:
for x2 in range(height):
    for x1 in range(width):
        v = np.array([x1, x2])
        new_vector = A.dot(v)
        print(f'{v} --> {new_vector}')
    print()

[0 0] --> [0 0]
[1 0] --> [1 0]
[2 0] --> [2 0]

[0 1] --> [ 0 -1]
[1 1] --> [ 1 -1]
[2 1] --> [ 2 -1]



In [7]:
for x2 in range(height):
    for x1 in range(width):
        v = np.array([x1, x2])
        new_vector = A.dot(v) + np.array([0, height-1])
        print(f'{v} --> {new_vector}')
    print()

[0 0] --> [0 1]
[1 0] --> [1 1]
[2 0] --> [2 1]

[0 1] --> [0 0]
[1 1] --> [1 0]
[2 1] --> [2 0]



In [9]:
for x2 in range(height):
    for x1 in range(width):
        v = np.array([x1, x2])
        new_x1, new_x2 = A.dot(v) + np.array([0, height-1])
        print(f'{v} --> ({new_x2}, {new_x1})')
    print()

[0 0] --> (1, 0)
[1 0] --> (1, 1)
[2 0] --> (1, 2)

[0 1] --> (0, 0)
[1 1] --> (0, 1)
[2 1] --> (0, 2)



In [11]:
output = np.zeros(shape=(height, width), dtype=int)

for x2 in range(height):
    for x1 in range(width):
        v = np.array([x1, x2])
        new_x1, new_x2 = A.dot(v) + np.array([0, height-1])
        output[new_x2, new_x1] = data[x2, x1]

output

array([[3, 4, 5],
       [0, 1, 2]])